defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha

version: 2
jobs:
  "MAKE DEPENDENCIES":
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  "RUN TESTS":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  "BUILD APP":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Download Keystore
          command: bash ./ci_scripts/download_keystore.sh
      - run:
          name: Build
          command: ./gradlew assembleCi
      - store_artifacts:
          path: app/build/outputs/apk/
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  "DEPLOY RELEASE":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
        name: Deploy APK.
        command: |
            bash ./ci_scripts/deploy-hockey.sh
            bash ./ci_scripts/deploy-fabric.sh
  "DEPLOY DEBUG":
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: |
              if [ ! -f @app/build/outputs/apk/ci/app-ci.apk ]; then
                  echo "File not found!"
              fi
workflows:
  version: 2
  build:
    jobs:
      - "MAKE DEPENDENCIES"
      - "RUN TESTS":
          requires:
            - "MAKE DEPENDENCIES"
      - "BUILD APP":
          requires:
            - "MAKE DEPENDENCIES"
      - "DEPLOY DEBUG":
          requires:
            - "MAKE DEPENDENCIES"
            - "BUILD APP"
            - "RUN TESTS"
          filters:
            branches:
              only: dev
      - "DEPLOY RELEASE":
          requires:
            - "MAKE DEPENDENCIES"
            - "BUILD APP"
            - "RUN TESTS"
          filters:
            branches:
              only: master
