version: 2
jobs:
  build:
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
      - save_cache:
        paths: - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  test:
    working_directory: ~/code
    steps:
      - run:
        name: Run Tests
        command: ./gradlew lint test
      - run:
        name: Run Unit Tests
        command: ./gradlew test
      - store_artifacts:
        path: app/build/reports
        destination: reports
      - store_test_results:
        path: app/build/test-results
  "MAKE APK":
    working_directory: ~/code
        steps:
          - run:
            name: Download Keystore
            command: bash ./ci_scripts/download_keystore.sh
          - run:
            name: Build
            command: ./gradlew assembleCi
          - store_artifacts:
            path: app/build/outputs/apk/
  "DEPLOY RELEASE":
    working_directory: ~/code
        steps:
          - deploy:
            name: Deploy APK.
            command: |
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        bash ./ci_scripts/deploy-hockey.sh
                        bash ./ci_scripts/deploy-fabric.sh
                      fi
workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - "MAKE APK"
      - "DEPLOY RELEASE"





