version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Keystore
          command: bash ./ci_scripts/download_keystore.sh
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build
          command: ./gradlew assembleCi
      - store_artifacts:
          path: app/build/outputs/apk/
      - deploy:
          name: Deploy APK.
          command: |
                               if [ "${CIRCLE_BRANCH}" == "master" ]; then
                                 bash ./ci_scripts/deploy-hockey.sh
                                 bash ./ci_scripts/deploy-fabric.sh
                               fi